# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dht_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhtresource',
            name='requests',
            field=models.IntegerField(default=0),
        ),
    ]
