# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dht', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_list',
            fields=[
                ('info_hash', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('file_list', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='keyword',
            fields=[
                ('key_word_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=20)),
                ('word_type', models.CharField(choices=[('1', 'normal'), ('2', 'porn')], default='1', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='node_shield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_ip', models.CharField(max_length=20, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_hash', models.CharField(max_length=40)),
                ('request_ip', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='resource_media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_hash', models.CharField(max_length=40)),
                ('frame_address', models.CharField(max_length=255)),
                ('frame_type', models.CharField(choices=[('1', 'normal'), ('2', 'porn')], default='1', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='resource_shield',
            fields=[
                ('info_hash', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='resource_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_hash', models.CharField(max_length=40)),
                ('key_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labeled_resource', to='dht.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('info_hash', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('1', 'normal'), ('2', 'porn')], default='1', max_length=20)),
                ('level', models.CharField(choices=[('1', 'serious'), ('2', 'not bad')], default='1', max_length=20)),
            ],
        ),
    ]
