# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dht', '0002_file_list_keyword_node_shield_request_resource_media_resource_shield_resource_text_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_text',
            name='key_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labeled_resource', to='dht.Keyword'),
        ),
    ]
