# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dht', '0004_auto_20170507_1645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='resource',
        ),
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='resource_text',
            name='key_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labeled_resource', to='dht.Keyword'),
        ),
    ]
