# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dht', '0005_auto_20170510_2101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='file_list',
        ),
        migrations.AlterField(
            model_name='resource_text',
            name='key_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labeled_resource', to='dht.Keyword'),
        ),
    ]
