# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dht', '0007_auto_20170510_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('ip', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=20)),
                ('img_src', models.CharField(max_length=255)),
                ('resource_num', models.IntegerField(auto_created=0)),
                ('anti_num', models.IntegerField(auto_created=0)),
                ('porn_num', models.IntegerField(auto_created=0)),
                ('vio_num', models.IntegerField(auto_created=0)),
                ('capture_time', models.DateTimeField(auto_now=True)),
                ('belonging', models.CharField(max_length=255)),
                ('feature', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='resource_text',
            name='key_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labeled_resource', to='dht.Keyword'),
        ),
    ]
