# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dht', '0008_auto_20170513_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='info_hash',
        ),
        migrations.AddField(
            model_name='type',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node',
            name='capture_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='node_shield',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='resource_shield',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='resource_text',
            name='key_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labeled_resource', to='dht.Keyword'),
        ),
    ]
