# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dht', '0010_auto_20170513_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchhash',
            options={},
        ),
        migrations.AlterField(
            model_name='resource_text',
            name='key_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labeled_resource', to='dht.Keyword'),
        ),
    ]
